import { NextResponse } from "next/server";
import { FieldValue } from "firebase-admin/firestore";
import { adminFirestore } from "@/lib/firebase/admin";

/**
 * What each reader browses, per section.
 *
 * The blog is public — there is no sign-in on /posts — so "each user" here is
 * a reader identity the browser keeps for itself (see lib/blog/reader-id.ts),
 * not an account. That is the honest scope: it distinguishes readers well
 * enough to hand someone back their own sections, and it deliberately cannot
 * be joined to a person.
 *
 * The write happens HERE rather than from the page because the browser holds
 * no Firestore credentials — the same reason every other write in this app
 * goes through the server. It also means the collection can never be written
 * with a section name the server did not recognise.
 */

const COLLECTION = "blog_reader_sections";

/**
 * Read counts, one document per ISO week.
 *
 * Bucketing by week is what lets the rail say "most read THIS WEEK" and mean
 * it. An all-time total would be a different claim, and a rolling window would
 * need a row per open rather than a counter.
 */
const STATS = "blog_stats";

/** ISO-8601 week key, e.g. 2026-W35. Weeks start Monday. */
export function isoWeek(d = new Date()): string {
  const t = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()));
  // Thursday decides the year an ISO week belongs to.
  t.setUTCDate(t.getUTCDate() + 4 - (t.getUTCDay() || 7));
  const start = new Date(Date.UTC(t.getUTCFullYear(), 0, 1));
  const week = Math.ceil(((t.getTime() - start.getTime()) / 86400000 + 1) / 7);
  return `${t.getUTCFullYear()}-W${String(week).padStart(2, "0")}`;
}

/** Slugs are generated by the admin service; accept only that shape. */
const SLUG = /^[a-z0-9][a-z0-9-]{0,120}$/;

/** The only sections that exist. Anything else is a client bug or a probe. */
const SECTIONS = new Set(["Recap", "Research desk", "Educational"]);

/** Reader ids are generated by the client; accept only the shape we issue. */
const ID = /^[a-z0-9-]{8,64}$/i;

type Counts = Record<string, number>;

export async function POST(req: Request) {
  let body: { readerId?: unknown; section?: unknown; slug?: unknown };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ ok: false, error: "bad_json" }, { status: 400 });
  }

  const readerId = typeof body.readerId === "string" ? body.readerId : "";
  const section = typeof body.section === "string" ? body.section : "";
  if (!ID.test(readerId)) {
    return NextResponse.json({ ok: false, error: "bad_reader" }, { status: 400 });
  }
  if (!SECTIONS.has(section)) {
    return NextResponse.json({ ok: false, error: "unknown_section" }, { status: 400 });
  }

  /*
   * A NESTED map, not a dotted key.
   *
   * set() treats "sections.Recap" as a field literally called that, dot
   * included — only update() reads dots as a path — so the counts were being
   * written beside `sections` rather than into it, and read back empty. With
   * merge:true a nested map merges field by field, which is the behaviour
   * wanted here: one section's count rises and the others are left alone.
   */
  const update: Record<string, unknown> = {
    sections: { [section]: FieldValue.increment(1) },
    lastSection: section,
    updatedAt: FieldValue.serverTimestamp(),
  };

  const slug = typeof body.slug === "string" ? body.slug : "";

  try {
    await adminFirestore.collection(COLLECTION).doc(readerId).set(update, { merge: true });
    if (slug && SLUG.test(slug)) {
      // Nested map, not a dotted key: set() treats "posts.foo" as a field
      // literally called that, so the count would land beside `posts` and read
      // back empty.
      await adminFirestore
        .collection(STATS)
        .doc(isoWeek())
        .set({ posts: { [slug]: FieldValue.increment(1) } }, { merge: true });
    }
  } catch (err) {
    // A reader's history is not worth failing their page over.
    return NextResponse.json({ ok: false, error: (err as Error).message }, { status: 500 });
  }
  return NextResponse.json({ ok: true });
}

export async function GET(req: Request) {
  const readerId = new URL(req.url).searchParams.get("readerId") ?? "";
  if (!ID.test(readerId)) {
    return NextResponse.json({ ok: false, error: "bad_reader" }, { status: 400 });
  }
  try {
    const doc = await adminFirestore.collection(COLLECTION).doc(readerId).get();
    const data = doc.exists ? doc.data() ?? {} : {};
    const raw = (data.sections ?? {}) as Counts;
    // Filter on the way out too: a section could have been renamed since the
    // row was written, and the page should not offer one that no longer exists.
    const sections: Counts = {};
    for (const [k, v] of Object.entries(raw)) {
      if (SECTIONS.has(k) && typeof v === "number") sections[k] = v;
    }
    const lastSection =
      typeof data.lastSection === "string" && SECTIONS.has(data.lastSection)
        ? data.lastSection
        : null;
    return NextResponse.json({ ok: true, sections, lastSection });
  } catch (err) {
    return NextResponse.json({ ok: false, error: (err as Error).message }, { status: 500 });
  }
}
